parameters:
  clipboard.class: Behat\ClipboardExtension\Clipboard\ClipboardDotNotationContainer
  clipboard.context_initializer.class: Behat\ClipboardExtension\Context\Initializer\ClipboardInitializer
  clipboard.transform.class: Behat\ClipboardExtension\Transformer\ClipboardArgumentTransformer

services:
  clipboard:
    class:  "%clipboard.class%"
    arguments:
      - "%clipboard.parameters.defaults%"

  clipboard.context_initializer:
    class: "%clipboard.context_initializer.class%"
    arguments: ["@clipboard"]
    tags:
      -  { name: context.initializer }

  clipboard.transform:
    class: "%clipboard.transform.class%"
    arguments:
      - "@clipboard"
      - "%clipboard.parameters%"
    tags:
      -  { name: transformation.argument_transformer, priority: 100 }


